builders:
  ratel_json:
    import: "package:ratel_generator/builder.dart"
    builder_factories: ["jsonBuilder"]
    build_extensions: {".dart": [".ratel_json.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
