builders:
  ratel:
    import: "package:ratel_generator/builder.dart"
    builder_factories: ["ratelBuilder"]
    build_extensions: {".dart": [".ratel.dart"]}
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        exclude:
          - "**.ratel.dart"
          - "**.g.dart"
