name: ratel_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/ratel
  - packages/ratel_cli
  - packages/ratel_cli/test/fixtures/broken_app
  - packages/ratel_cli/test/fixtures/kitchen_sink
  - packages/ratel_orm
