name: ratel
description: A back end framework with dart.
version: 1.0.2
homepage: https://github.com/Ratel-Dart/Ratel.git

environment:
  sdk: ^3.5.4

dependencies:
  reflectable: ^3.0.0
  postgres: ^3.5.0
  dart_jsonwebtoken: ^3.1.1
  
