name: Ratel
description: A back-end framework with annotations
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  reflectable: ^3.0.0
  postgres: ^3.5.0
  dart_jsonwebtoken: ^3.1.1
  
assets:
  - .env
