include: package:lints/recommended.yaml

analyzer:
  exclude:
    - test/fixtures/broken_orm/**
    - test/fixtures/orm_app/**
    - test/fixtures/orm_only/**
  errors:
    avoid_print: warning
    empty_catches: warning
    directives_ordering: warning
    unnecessary_library_directive: warning
    unnecessary_library_name: warning
    implementation_imports: warning
    avoid_relative_lib_imports: warning
    file_names: warning

linter:
  rules:
    - avoid_print
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - unnecessary_library_directive
    - unnecessary_library_name
