import 'dart:io';

import 'package:path/path.dart' as p;

import 'pubspec_reader.dart';
import 'ratel_project.dart';

abstract final class Leftovers {
  static const _obsoleteDependencies = ['build_runner', 'ratel_generator'];

  static void report(RatelProject project) {
    final files = _generatedFiles(project.root);
    if (files.isNotEmpty) {
      stdout.writeln(
        '[ratel] these files were generated by an older ratel and can be '
        'deleted:',
      );
      for (final file in files) {
        stdout.writeln('  ${p.relative(file, from: project.root)}');
      }
    }
    final pubspec = project.pubspec.readAsStringSync();
    final obsolete = _obsoleteDependencies
        .where((name) => PubspecReader.declaresDependency(pubspec, name))
        .toList();
    if (obsolete.isNotEmpty) {
      stdout.writeln(
        '[ratel] ${obsolete.join(' and ')} are no longer needed by Ratel and '
        'can be removed from pubspec.yaml.',
      );
    }
  }

  static List<String> _generatedFiles(String root) {
    final found = <String>[];
    for (final name in const ['lib', 'bin', 'example', 'test']) {
      final directory = Directory(p.join(root, name));
      if (!directory.existsSync()) continue;
      for (final entity
          in directory.listSync(recursive: true, followLinks: false)) {
        if (entity is File && entity.path.endsWith('.ratel.dart')) {
          found.add(entity.path);
        }
      }
    }
    return found..sort();
  }
}
