import 'package:analyzer/dart/analysis/session.dart';

import '../cli/ratel_cli_version.dart';
import '../engine/analysis/runtime_contract_reader.dart';
import '../engine/project_analyzer.dart';
import 'project_runtimes.dart';

abstract final class RuntimeCompatibility {
  static const _ratel = 'package:ratel/ratel.dart';
  static const _ratelOrm = 'package:ratel_orm/ratel_orm.dart';

  static Future<({ProjectRuntimes? runtimes, String? error})> check(
    ProjectAnalyzer analyzer,
  ) async {
    final session = analyzer.session;
    final framework = await RuntimeContractReader.resolves(session, _ratel);
    if (framework) {
      final error = await _framework(session);
      if (error != null) return (runtimes: null, error: error);
    }
    final orm = await RuntimeContractReader.resolves(
      session,
      RuntimeContractReader.ormLibrary,
    );
    if (orm) {
      final error = await _orm(session);
      if (error != null) return (runtimes: null, error: error);
    }
    if (framework || orm) {
      return (
        runtimes: ProjectRuntimes(framework: framework, orm: orm),
        error: null,
      );
    }
    if (await RuntimeContractReader.resolves(session, _ratelOrm)) {
      return (
        runtimes: null,
        error: 'This project resolves a ratel_orm that predates entity '
            'mappers generated by the CLI (it has no '
            'package:ratel_orm/runtime.dart). Run: dart pub upgrade ratel_orm',
      );
    }
    return (
      runtimes: null,
      error: 'This project depends on neither ratel nor ratel_orm. Run: dart '
          'pub add ratel (HTTP) or dart pub add ratel_orm (database).',
    );
  }

  static Future<String?> _framework(AnalysisSession session) async {
    final contract = await RuntimeContractReader.read(
      session,
      library: RuntimeContractReader.ratelLibrary,
      runtime: RuntimeContractReader.ratelRuntime,
    );
    if (contract == RatelCliVersion.contract) return null;
    if (contract != null) {
      return 'ratel_cli ${RatelCliVersion.current} generates code for runtime '
          'contract ${RatelCliVersion.contract}, but this app resolves a ratel '
          'with contract $contract. Install the matching CLI: '
          'dart pub global activate ratel_cli <the ratel version in '
          'pubspec.lock>';
    }
    return 'This app resolves a ratel that predates generation by the CLI '
        '(it has no package:ratel/runtime.dart). Run: dart pub upgrade ratel';
  }

  static Future<String?> _orm(AnalysisSession session) async {
    final contract = await RuntimeContractReader.read(
      session,
      library: RuntimeContractReader.ormLibrary,
      runtime: RuntimeContractReader.ormRuntime,
    );
    if (contract == RatelCliVersion.ormContract) return null;
    final resolved = contract == null
        ? 'a ratel_orm whose runtime declares no contract'
        : 'a ratel_orm with contract $contract';
    return 'ratel_cli ${RatelCliVersion.current} generates entity mappers for '
        'ratel_orm runtime contract ${RatelCliVersion.ormContract}, but this '
        'project resolves $resolved. Install a ratel_cli that supports it: '
        'dart pub global activate ratel_cli';
  }
}
